//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceIF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaceIF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0000 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0001 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0002 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0003 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0004 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0005 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0006 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0007 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0008 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0008", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0009 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0009", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0010 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0011 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0012 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0013 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0013", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0014 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0014", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0015 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0015", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0016 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0016", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0017 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0017", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0018 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0018", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0019 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0019", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0020 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0020", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0021 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0021", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0022 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0022", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0023 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0023", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0024 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0025 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0025", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0026 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0026", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0027 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0027", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0028 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0028", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0029 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0029", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0030 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0030", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0031 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0031", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0032 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0032", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0033 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0033", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0034 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0034", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0035 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0035", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0036 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0036", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0037 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0037", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0038 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0038", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0039 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0039", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0040 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0040", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0041 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0041", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0042 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0042", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0043 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0043", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0044 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0044", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0045 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0045", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0046 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0046", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAXI_CLEAN_ALLD0047 {
            get {
                object obj = ResourceManager.GetObject("TAXI_CLEAN_ALLD0047", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
